server:
  port: 8081
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hyperprof?serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
br:
  com:
    treinaweb:
      hyperprof:
        core:
          services:
            token:
              jjwt:
                accessTokenSigingKey: 2kYuOv~<F;`H7uMGq`6Kq[t`I&d{lcXB#HKTxWb}~v7_U.>BSQ7:qGX_&oB:1n%
                accessTokenExpirationInSeconds: 30
                refreshTokenSigingKey: He*&VJ&6t|1{j;pHXY_$M^s?q[lDbwiT%qsS#)6A9K'Z{r*Dz{4D"|ZKlj9L!u&
                refreshTokenExpirationInSeconds: 60
